- name: Install .NET 6 runtime
  run: |
    sudo apt-get update
    sudo apt-get install -y dotnet-runtime-6.0

- name: Download Il2CppDumper (net6)
  run: |
    set -e
    curl -fsSL -o Il2CppDumper.zip "https://github.com/Perfare/Il2CppDumper/releases/download/v6.7.46/Il2CppDumper-net6-v6.7.46.zip"
    # sanity check to avoid HTML/9-byte downloads
    test $(stat -c%s Il2CppDumper.zip) -gt 100000
    unzip -q Il2CppDumper.zip -d Il2CppDumper

- name: Run Il2CppDumper
  run: |
    dotnet Il2CppDumper/Il2CppDumper.dll libil2cpp.so assets/bin/Data/Managed/Metadata/global-metadata.dat --output dumper_output

