name: FreeFire-Specialized-Il2CppDumping-Fixed

on:
  push:
  workflow_dispatch:

jobs:
  dump-freefire:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Install basic tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl file

      - name: Download specialized Free Fire Il2CppDumper
        run: |
          curl -fsSL -o Il2CppDumper-for-Free-Fire.zip "https://github.com/tien0246/Il2CppDumper-Free-Fire/releases/download/1.0/Il2CppDumper-for-Free-Fire.zip"
          unzip -q Il2CppDumper-for-Free-Fire.zip -d FreeFire-Il2CppDumper

      - name: Download Free Fire Max APK
        run: |
          curl -fsSL -o freefire-max.apk "https://files.catbox.moe/2326p1.apk"

      - name: Extract APK and get IL2CPP files
        run: |
          mkdir -p apk_extracted
          unzip -q freefire-max.apk -d apk_extracted
          cp apk_extracted/lib/arm64-v8a/libil2cpp.so .
          mkdir -p assets/bin/Data/Managed/Metadata
          cp apk_extracted/assets/bin/Data/Managed/Metadata/global-metadata.dat assets/bin/Data/Managed/Metadata/

      - name: Verify extracted files
        run: |
          echo "libil2cpp.so size: $(stat -c%s libil2cpp.so) bytes"
          echo "global-metadata.dat size: $(stat -c%s assets/bin/Data/Managed/Metadata/global-metadata.dat) bytes"
          file libil2cpp.so
          file assets/bin/Data/Managed/Metadata/global-metadata.dat

      - name: Create output directory
        run: mkdir -p dumper_output

      - name: Run specialized Free Fire Il2CppDumper
        run: |
          echo "Running specialized Free Fire Il2CppDumper with .NET 7..."
          set +e
          dotnet FreeFire-Il2CppDumper/Il2CppDumper.dll libil2cpp.so assets/bin/Data/Managed/Metadata/global-metadata.dat dumper_output
          exit_code=$?
          set -e
          
          echo "Specialized dumper exit code: $exit_code"
          
          if [ -d "dumper_output" ] && [ "$(ls -A dumper_output 2>/dev/null)" ]; then
            echo "SUCCESS: Specialized Free Fire dumper worked!"
            cs_files=$(find dumper_output -name '*.cs' 2>/dev/null | wc -l)
            json_files=$(find dumper_output -name '*.json' 2>/dev/null | wc -l)
            py_files=$(find dumper_output -name '*.py' 2>/dev/null | wc -l)
            echo "Generated files - C#: $cs_files, JSON: $json_files, Python: $py_files"
            ls -la dumper_output/
          else
            echo "Specialized dumper failed to generate output"
          fi

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FreeFire-Specialized-Dump-Results
          path: dumper_output/
          retention-days: 30
